services:
  - type: web
    name: indicadores-ajudantes
    env: python
    buildCommand: |
      apt-get update && apt-get install -y freetds-dev gcc && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: "SUA_STRING_DE_CONEXÃO_DO_SQL_SERVER"
