services:
  - type: web
    name: indicadores-ajudantes
    env: python
    pythonVersion: 3.11.9
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: "SUA_STRING_DE_CONEXÃO_DO_SQL_SERVER"
